[package]
name = "misterdrillerterm"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
dirs = "6.0.0"
image = { version = "0.25.10", default-features = false, features = ["png"] }
rand = "0.10.2"
rand_chacha = "0.10.0"
ratatui = "0.30.2"
rodio = "0.22.2"
rusqlite = { version = "0.32", features = ["bundled"] }
